test:
  stage: test
  image: openjdk:17-slim           # this image is signed
  before_script:
    - apt-get update               # install Gradle on the fly
    - apt-get install -y gradle
  script:
    - gradle --no-daemon test      # now use the system Gradle
  cache:
    paths:
      - .gradle/caches             # still cache deps
  artifacts:
    paths:
      - app/build/reports
  only:
    - branches
    - merge_requests