test:
  stage: test
  image: gradle:8.10-jdk17            # Gradle 8.10 already inside ⇒ no download
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    paths:                            # still cache downloaded deps
      - .gradle/wrapper
      - .gradle/caches
  script:
    - gradle --no-daemon test         # wrapper no longer needed
  artifacts:
    paths:
      - app/build/reports
  only:
    - branches
    - merge_requests