stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/java/jdk:17-ubuntu  # signed, contains OpenJDK 17
  before_script:
    # Install Gradle from apt (only ~10 s) so 'gradle' is on the PATH
    - apt-get update && apt-get install -y gradle
  script:
    - gradle --no-daemon test
  cache:
    paths:
      - .gradle/caches
  artifacts:
    paths:
      - app/build/reports
  only:
    - branches
    - merge_requests
