test:
  stage: test
  image: openjdk:17-slim        # signed image ⇒ no “missing signature” error
  script:
    - chmod +x ./gradlew        # Windows repo safeguard
    - ./gradlew --no-daemon test
  artifacts:
    paths:
      - app/build/reports
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  only:
    - branches
    - merge_requests
