/*
 * This file was generated by the Gradle 'init' task, and manually manipulated...
 */
import org.gradle.api.tasks.SourceSetContainer

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2")
}

application {
    // Define the main class for the application.
    mainClass.set("GameLauncher")
}
